### ISSUE TITLE
Problem z gminą Gruta @iMPA

### ISSUE THREAD

**Issue by zibik** [wiktorn/osm-addr-tools#19]
Przygotowując import: ./merger.py --impa gruta skrypt nie połączył adresów z budynkami. Nie zauważyłem tego faktu robiąc import, skutkiem czego do bazy trafiły adresy niepołączone z obrysami.
Przykład: 
- https://www.openstreetmap.org/node/3458269006
- https://www.openstreetmap.org/way/179050167
Sprawdziłem dzisiaj i jest nadal tak samo, a nawet gorzej, bo merger nie wyklucza (nie zauważa) adresów już wrzuconych do bazy.

Dla testu sprawdziłem analogicznie zaleszany@iMPA i tam się ładnie integruje z obrysami.

**Comment by wiktorn** [comment]
Kłopot jest, bo dla TERC, zwracany jest obszar zarówno gminy Gruta, jak i miasto Brodnica.
http://overpass-turbo.eu/s/92I

Poprawiłem kod by:
1. Raportował, jak się nazywa relacja, z której wyciągnął obszar, na którym pracuje
2. By szukając relacji, być pewnym że zaczyna się ona podanym ciągiem znaków, a nie tylko zawiera podany ciąg znaków

Nastomiast TERC Brodnicy trzeba poprawić.

**Comment by wiktorn** [comment]
W sumie - to mogę jeszcze dodać takie rozwiązanie, by w przypadku, gdy znalezione zostanie więcej niż jedna relacja dla danego terc (co może się zdarzyć w przypadku gmin miejskich i wiejskich, a gdy tylko jedna jest w iMPA), by zrobić połączenie wszystkich obszarów.

przy okazji też, w takiej sytuacji pojawiałby się warning.

**Comment by zibik** [comment]
Chyba nie ma potrzeby, by to było otwarte...
